/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
void quickSort(int *array , int low , int high ) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
void swap(int *a , int *b ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void exit(int status ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
typedef struct _IO_FILE FILE;
extern int close(int filedes ) ;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern void *malloc(unsigned int size ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
int partition(int *array , int low , int high ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void printArray(int *array , int size ) ;
void megaInit(void) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int data[7] ;
  int n ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  data[0] = 8;
  data[1] = 7;
  data[2] = 2;
  data[3] = 1;
  data[4] = 0;
  data[5] = 9;
  data[6] = 6;
  n = (int )(sizeof(data) / sizeof(data[0]));
  printArray(data, n);
  quickSort(data, 0, ((n & ~ 1) << 1) - (n ^ 1));
  printArray(data, n);
  return (0);
}
}
void megaInit(void) 
{ 


  {

}
}
int partition(int *array , int low , int high ) 
{ 
  int pivot ;
  int i ;
  int j ;

  {
  pivot = *(array + high);
  i = (low + ~ 1) + 1;
  j = low;
  while (((unsigned int )(((((high - j) & - (high >= j)) + ((high - j) & - (high >= j))) & (((high - j) & - (high >= j)) >> 31)) - ((high - j) & - (high >= j))) >> 31U) & 1) {
    if (((unsigned int )((*(array + j) | ~ pivot) & ((*(array + j) ^ pivot) | ~ (pivot - *(array + j)))) >> 31U) & 1) {
      i = ((i ^ ~ 1) + ((i | 1) + (i | 1))) + 1;
      swap(array + i, array + j);
    }
    j = ((j ^ ~ 1) + ((j | 1) + (j | 1))) + 1;
  }
  swap(array + ((i - ~ 1) - 1), array + high);
  return (((i ^ ~ 1) + ((i | 1) << 1)) + 1);
}
}
void printArray(int *array , int size ) 
{ 
  int i ;

  {
  i = 0;
  while (i < size) {
    printf((char const   */* __restrict  */)"%d  ", *(array + i));
    i ++;
  }
  printf((char const   */* __restrict  */)"\n");
  return;
}
}
void swap(int *a , int *b ) 
{ 
  int t ;

  {
  t = *a;
  *a = *b;
  *b = t;
  return;
}
}
void quickSort(int *array , int low , int high ) 
{ 
  int pi ;
  int tmp ;

  {
  if (((unsigned int )(((((high - low) & - (high >= low)) >> 31) - ((high - low) & - (high >= low))) ^ (((high - low) & - (high >= low)) >> 31)) >> 31U) & 1) {
    tmp = partition(array, low, high);
    pi = tmp;
    quickSort(array, low, (pi ^ 1) - ((~ pi & 1) << 1));
    quickSort(array, ((pi ^ ~ 1) + ((pi | 1) << 1)) + 1, high);
  }
  return;
}
}
