/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
void quickSort(int *array , int low , int high ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
void swap(int *a , int *b ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void free(void *ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void signal(int sig , void *func ) ;
extern void exit(int status ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern double ceil(double x ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern void *malloc(unsigned int size ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
int partition(int *array , int low , int high ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void printArray(int *array , int size ) ;
void megaInit(void) ;
int partition(int *array , int low , int high ) 
{ 
  int pivot ;
  int i ;
  int j ;
  unsigned long _1_partition_next ;

  {
  {
  _1_partition_next = 4UL;
  }
  while (1) {
    switch (_1_partition_next) {
    case 4: 
    pivot = *(array + high);
    i = low - 1;
    j = low;
    {
    _1_partition_next = 2UL;
    }
    break;
    case 8: ;
    return (i + 1);
    break;
    case 3: 
    swap(array + (i + 1), array + high);
    {
    _1_partition_next = 8UL;
    }
    break;
    case 6: 
    j ++;
    {
    _1_partition_next = 2UL;
    }
    break;
    case 5: 
    i ++;
    swap(array + i, array + j);
    {
    _1_partition_next = 6UL;
    }
    break;
    case 7: ;
    if (*(array + j) <= pivot) {
      {
      _1_partition_next = 5UL;
      }
    } else {
      {
      _1_partition_next = 6UL;
      }
    }
    break;
    case 2: ;
    if (j < high) {
      {
      _1_partition_next = 7UL;
      }
    } else {
      {
      _1_partition_next = 3UL;
      }
    }
    break;
    }
  }
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int data[7] ;
  int n ;
  int _BARRIER_0 ;
  unsigned long _1_main_next ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  {
  _1_main_next = 1UL;
  }
  while (1) {
    switch (_1_main_next) {
    case 1: 
    data[0] = 8;
    data[1] = 7;
    data[2] = 2;
    data[3] = 1;
    data[4] = 0;
    data[5] = 9;
    data[6] = 6;
    n = (int )(sizeof(data) / sizeof(data[0]));
    printArray(data, n);
    quickSort(data, 0, n - 1);
    printArray(data, n);
    {
    _1_main_next = 0UL;
    }
    break;
    case 0: ;
    return (0);
    break;
    }
  }
}
}
void swap(int *a , int *b ) 
{ 
  int t ;
  unsigned long _1_swap_next ;

  {
  {
  _1_swap_next = 0UL;
  }
  while (1) {
    switch (_1_swap_next) {
    case 1: ;
    return;
    break;
    case 0: 
    t = *a;
    *a = *b;
    *b = t;
    {
    _1_swap_next = 1UL;
    }
    break;
    }
  }
}
}
void megaInit(void) 
{ 


  {

}
}
void printArray(int *array , int size ) 
{ 
  int i ;

  {
  i = 0;
  while (i < size) {
    printf((char const   */* __restrict  */)"%d  ", *(array + i));
    i ++;
  }
  printf((char const   */* __restrict  */)"\n");
  return;
}
}
void quickSort(int *array , int low , int high ) 
{ 
  int pi ;
  int tmp ;
  unsigned long _1_quickSort_next ;

  {
  {
  _1_quickSort_next = 0UL;
  }
  while (1) {
    switch (_1_quickSort_next) {
    case 1: 
    tmp = partition(array, low, high);
    pi = tmp;
    quickSort(array, low, pi - 1);
    quickSort(array, pi + 1, high);
    {
    _1_quickSort_next = 2UL;
    }
    break;
    case 0: ;
    if (low < high) {
      {
      _1_quickSort_next = 1UL;
      }
    } else {
      {
      _1_quickSort_next = 2UL;
      }
    }
    break;
    case 2: ;
    return;
    break;
    }
  }
}
}
